### PR TITLE
Debug quadruped gaits

### PR DESCRIPTION
**Pull request by wxmerkt**
On top of #18. Starts documenting which configuration pairs work / don't work and adds an anymal_trot example which fails. More details via email.

### CODE REVIEW

**Review by nim65s — APPROVED** [review]
thanks :)

**Comment by MaximilienNaveau** [comment]
Can we merge this and the other PRs?
May I have some rights on this repo?

**Comment by MaximilienNaveau** [comment]
@wxmerkt Could you fix the PR so we can merge it or do you want me to handle it?

**Comment by wxmerkt** [comment]
We are preparing for the quadruped trial tomorrow and then I'm traveling to Philadelphia - so I wont have time to fix the conflicts. If the changes get preserved, can you please look into it? Many thanks!

**Pull request merged**
