### PR TITLE
Mnaveau/format

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
Simply format the code using black

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
@nim65s it is not really necessary to review this as it's just pure code formatting, I made sure the example were running properly.
I will merge soon.

**Comment by MaximilienNaveau** [comment]
There are a lot of small fixes to do that black do not:
remove unused import, delete unused variables, etc.

**Comment by nim65s** [comment]
I would suggest to keep black default line length, as this is what we are already doing in all other places. 

> Pro-tip: If you're asking yourself "Do I need to configure anything?" the answer is "No". Black is all about sensible defaults. Applying those defaults will have your code in compliance with many other Black formatted projects.

**Comment by MaximilienNaveau** [comment]
Reformatted using `black .`

**Pull request merged**
